package com.store.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Pessoa")
public class Registro implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "REGISTRO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "REGISTRO_ID_SEQ", name = "REGISTRO_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String nome;

	public Registro() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public Registro(java.lang.Long id, java.lang.String nome) {
		this.id = id;
		this.nome = nome;
	}

}